---
- hosts: node2
  strategy: free
  gather_facts: true
  tasks:
  - name: Creating Ansible User
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding control address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.60 control.node.example.com control
      create: yes
  - name: Adding node1 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.61 ans1.node.example.com node1
      create: yes
  - name: Adding node2 IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.62 ans2.node.example.com node2
      create: yes
  - name: Configuring network
    command: nmcli con mod "System enp0s8" ipv4.addresses 192.168.55.62/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Restarting Network
    command: nmcli con up "System enp0s8" 
  - name: Generating RSA Key
    command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    args:
      creates: /etc/ssh/ssh_host_rsa_key