---
- name: 
  hosts: node[1:3].example.com

  tasks:
  - name: disable NetworkManager
    service:
      name: NetworkManager
      enabled: false
      state: stopped
  - name: edit file
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet net.ifnames=0 biosdevname=0"'
  - name: rewrite grub
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
...
