---
- hosts: node1.example.com
  tasks:
    - name: Create a file
      file:
        path: /tmp/file
        state: touch
      register: output
    - debug: msg="Register output is {{output}}"
    - name: edit file
      lineinfile:
        path: /tmp/file
        line: "{{output.uid}}"
